-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."BangDeXuat"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    nguoi_de_xuat_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    loai_de_xuat character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    thang integer,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    data_danh_hieu jsonb,
    data_thanh_tich jsonb,
    data_nien_han jsonb,
    data_cong_hien jsonb,
    files_attached jsonb,
    ghi_chu text COLLATE pg_catalog."default",
    rejection_reason text COLLATE pg_catalog."default",
    nguoi_duyet_id character varying(30) COLLATE pg_catalog."default",
    ngay_duyet timestamp(0) without time zone,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    files_attached_admin jsonb,
    CONSTRAINT "BangDeXuat_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ChucVu"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    ten_chuc_vu character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_manager boolean NOT NULL DEFAULT false,
    he_so_chuc_vu double precision NOT NULL DEFAULT 0,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "ChucVu_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CoQuanDonVi"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    ma_don_vi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ten_don_vi character varying(255) COLLATE pg_catalog."default" NOT NULL,
    so_luong integer NOT NULL DEFAULT 0,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "CoQuanDonVi_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."DanhHieuDonViHangNam"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    nam integer NOT NULL,
    danh_hieu character varying(50) COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    nhan_bkbqp boolean NOT NULL DEFAULT false,
    so_quyet_dinh_bkbqp character varying(100) COLLATE pg_catalog."default",
    ghi_chu_bkbqp text COLLATE pg_catalog."default",
    nhan_bkttcp boolean NOT NULL DEFAULT false,
    so_quyet_dinh_bkttcp character varying(100) COLLATE pg_catalog."default",
    ghi_chu_bkttcp text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    nguoi_tao_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nguoi_duyet_id character varying(30) COLLATE pg_catalog."default",
    ngay_duyet timestamp(0) without time zone,
    ghi_chu text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "DanhHieuDonViHangNam_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."DanhHieuHangNam"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    danh_hieu character varying(20) COLLATE pg_catalog."default",
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    nhan_bkbqp boolean NOT NULL DEFAULT false,
    so_quyet_dinh_bkbqp character varying(100) COLLATE pg_catalog."default",
    ghi_chu_bkbqp text COLLATE pg_catalog."default",
    nhan_cstdtq boolean NOT NULL DEFAULT false,
    so_quyet_dinh_cstdtq character varying(100) COLLATE pg_catalog."default",
    ghi_chu_cstdtq text COLLATE pg_catalog."default",
    nhan_bkttcp boolean NOT NULL DEFAULT false,
    so_quyet_dinh_bkttcp character varying(100) COLLATE pg_catalog."default",
    ghi_chu_bkttcp text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "DanhHieuHangNam_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."DonViTrucThuoc"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    ma_don_vi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ten_don_vi character varying(255) COLLATE pg_catalog."default" NOT NULL,
    so_luong integer NOT NULL DEFAULT 0,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "DonViTrucThuoc_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."FileQuyetDinh"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    ngay_ky date NOT NULL,
    nguoi_ky character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(500) COLLATE pg_catalog."default",
    loai_khen_thuong character varying(50) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "FileQuyetDinh_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HoSoCongHien"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    hcbvtq_total_months integer NOT NULL DEFAULT 0,
    months_07 integer NOT NULL DEFAULT 0,
    months_08 integer NOT NULL DEFAULT 0,
    months_0910 integer NOT NULL DEFAULT 0,
    hcbvtq_hang_ba_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hcbvtq_hang_ba_ngay date,
    hcbvtq_hang_nhi_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hcbvtq_hang_nhi_ngay date,
    hcbvtq_hang_nhat_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hcbvtq_hang_nhat_ngay date,
    goi_y text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "HoSoCongHien_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HoSoDonViHangNam"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    nam integer NOT NULL,
    tong_dvqt integer NOT NULL DEFAULT 0,
    tong_dvqt_json jsonb,
    dvqt_lien_tuc integer NOT NULL DEFAULT 0,
    du_dieu_kien_bk_tong_cuc boolean NOT NULL DEFAULT false,
    du_dieu_kien_bk_thu_tuong boolean NOT NULL DEFAULT false,
    goi_y text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "HoSoDonViHangNam_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HoSoHangNam"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    tong_cstdcs integer NOT NULL DEFAULT 0,
    tong_nckh integer NOT NULL DEFAULT 0,
    tong_cstdcs_json jsonb,
    tong_nckh_json jsonb,
    cstdcs_lien_tuc integer NOT NULL DEFAULT 0,
    nckh_lien_tuc integer NOT NULL DEFAULT 0,
    bkbqp_lien_tuc integer NOT NULL DEFAULT 0,
    cstdtq_lien_tuc integer NOT NULL DEFAULT 0,
    du_dieu_kien_bkbqp boolean NOT NULL DEFAULT false,
    du_dieu_kien_cstdtq boolean NOT NULL DEFAULT false,
    du_dieu_kien_bkttcp boolean NOT NULL DEFAULT false,
    goi_y text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "HoSoHangNam_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HoSoNienHan"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    hccsvv_hang_ba_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hccsvv_hang_ba_ngay date,
    hccsvv_hang_nhi_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hccsvv_hang_nhi_ngay date,
    hccsvv_hang_nhat_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CHUA_DU'::character varying,
    hccsvv_hang_nhat_ngay date,
    goi_y text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "HoSoNienHan_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HuanChuongQuanKyQuyetThang"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    thang integer NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    thoi_gian jsonb,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "HuanChuongQuanKyQuyetThang_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."KhenThuongDotXuat"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    loai character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'KHEN_THUONG_DOT_XUAT'::character varying,
    doi_tuong character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CA_NHAN'::character varying,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default",
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    hinh_thuc_khen_thuong character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    files_dinh_kem jsonb,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "KhenThuongDotXuat_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."KhenThuongHCBVTQ"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    danh_hieu character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    thang integer NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    thoi_gian_nhom_0_7 jsonb,
    thoi_gian_nhom_0_8 jsonb,
    thoi_gian_nhom_0_9_1_0 jsonb,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "KhenThuongHCBVTQ_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."KhenThuongHCCSVV"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    danh_hieu character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    thang integer NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    thoi_gian jsonb,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "KhenThuongHCCSVV_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."KyNiemChuongVSNXDQDNDVN"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    thang integer NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    thoi_gian jsonb,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "KyNiemChuongVSNXDQDNDVN_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."LichSuChucVu"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    chuc_vu_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    he_so_chuc_vu double precision NOT NULL DEFAULT 0,
    ngay_bat_dau date NOT NULL,
    ngay_ket_thuc date,
    so_thang integer,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "LichSuChucVu_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."QuanNhan"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    cccd character varying(20) COLLATE pg_catalog."default",
    ho_ten character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gioi_tinh character varying(10) COLLATE pg_catalog."default",
    ngay_sinh date,
    que_quan_2_cap character varying(255) COLLATE pg_catalog."default",
    que_quan_3_cap character varying(255) COLLATE pg_catalog."default",
    tru_quan character varying(255) COLLATE pg_catalog."default",
    cho_o_hien_nay character varying(255) COLLATE pg_catalog."default",
    co_quan_don_vi jsonb,
    ngay_nhap_ngu date,
    ngay_xuat_ngu date,
    ngay_vao_dang date,
    ngay_vao_dang_chinh_thuc date,
    so_the_dang_vien character varying(50) COLLATE pg_catalog."default",
    so_dien_thoai character varying(20) COLLATE pg_catalog."default",
    cap_bac character varying(50) COLLATE pg_catalog."default",
    co_quan_don_vi_id character varying(30) COLLATE pg_catalog."default",
    don_vi_truc_thuoc_id character varying(30) COLLATE pg_catalog."default",
    chuc_vu_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "QuanNhan_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."SystemLog"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nguoi_thuc_hien_id character varying(30) COLLATE pg_catalog."default",
    actor_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    action character varying(50) COLLATE pg_catalog."default" NOT NULL,
    resource character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tai_nguyen_id character varying(30) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default" NOT NULL,
    payload jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SystemLog_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."SystemSetting"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "SystemSetting_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TaiKhoan"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default",
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "refreshToken" text COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "TaiKhoan_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ThanhTichKhoaHoc"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quan_nhan_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nam integer NOT NULL,
    loai character varying(10) COLLATE pg_catalog."default" NOT NULL,
    mo_ta character varying(500) COLLATE pg_catalog."default" NOT NULL,
    cap_bac character varying(50) COLLATE pg_catalog."default",
    chuc_vu character varying(255) COLLATE pg_catalog."default",
    ghi_chu text COLLATE pg_catalog."default",
    so_quyet_dinh character varying(100) COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(0) without time zone NOT NULL,
    CONSTRAINT "ThanhTichKhoaHoc_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ThongBao"
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nguoi_nhan_id character varying(30) COLLATE pg_catalog."default",
    recipient_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message character varying(500) COLLATE pg_catalog."default" NOT NULL,
    resource character varying(50) COLLATE pg_catalog."default",
    tai_nguyen_id character varying(30) COLLATE pg_catalog."default",
    link character varying(255) COLLATE pg_catalog."default",
    is_read boolean NOT NULL DEFAULT false,
    nhat_ky_he_thong_id character varying(30) COLLATE pg_catalog."default",
    "createdAt" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAt" timestamp(0) without time zone,
    CONSTRAINT "ThongBao_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."BangDeXuat"
    ADD CONSTRAINT "BangDeXuat_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."BangDeXuat"
    ADD CONSTRAINT "BangDeXuat_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."BangDeXuat"
    ADD CONSTRAINT "BangDeXuat_nguoi_de_xuat_id_fkey" FOREIGN KEY (nguoi_de_xuat_id)
    REFERENCES public."TaiKhoan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."BangDeXuat"
    ADD CONSTRAINT "BangDeXuat_nguoi_duyet_id_fkey" FOREIGN KEY (nguoi_duyet_id)
    REFERENCES public."TaiKhoan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."ChucVu"
    ADD CONSTRAINT "ChucVu_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."ChucVu"
    ADD CONSTRAINT "ChucVu_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."DanhHieuDonViHangNam"
    ADD CONSTRAINT "DanhHieuDonViHangNam_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."DanhHieuDonViHangNam"
    ADD CONSTRAINT "DanhHieuDonViHangNam_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."DanhHieuDonViHangNam"
    ADD CONSTRAINT "DanhHieuDonViHangNam_so_quyet_dinh_bkbqp_fkey" FOREIGN KEY (so_quyet_dinh_bkbqp)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuDonViHangNam_so_quyet_dinh_bkbqp_idx"
    ON public."DanhHieuDonViHangNam"(so_quyet_dinh_bkbqp);


ALTER TABLE IF EXISTS public."DanhHieuDonViHangNam"
    ADD CONSTRAINT "DanhHieuDonViHangNam_so_quyet_dinh_bkttcp_fkey" FOREIGN KEY (so_quyet_dinh_bkttcp)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuDonViHangNam_so_quyet_dinh_bkttcp_idx"
    ON public."DanhHieuDonViHangNam"(so_quyet_dinh_bkttcp);


ALTER TABLE IF EXISTS public."DanhHieuDonViHangNam"
    ADD CONSTRAINT "DanhHieuDonViHangNam_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuDonViHangNam_so_quyet_dinh_idx"
    ON public."DanhHieuDonViHangNam"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."DanhHieuHangNam"
    ADD CONSTRAINT "DanhHieuHangNam_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."DanhHieuHangNam"
    ADD CONSTRAINT "DanhHieuHangNam_so_quyet_dinh_bkbqp_fkey" FOREIGN KEY (so_quyet_dinh_bkbqp)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuHangNam_so_quyet_dinh_bkbqp_idx"
    ON public."DanhHieuHangNam"(so_quyet_dinh_bkbqp);


ALTER TABLE IF EXISTS public."DanhHieuHangNam"
    ADD CONSTRAINT "DanhHieuHangNam_so_quyet_dinh_bkttcp_fkey" FOREIGN KEY (so_quyet_dinh_bkttcp)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuHangNam_so_quyet_dinh_bkttcp_idx"
    ON public."DanhHieuHangNam"(so_quyet_dinh_bkttcp);


ALTER TABLE IF EXISTS public."DanhHieuHangNam"
    ADD CONSTRAINT "DanhHieuHangNam_so_quyet_dinh_cstdtq_fkey" FOREIGN KEY (so_quyet_dinh_cstdtq)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuHangNam_so_quyet_dinh_cstdtq_idx"
    ON public."DanhHieuHangNam"(so_quyet_dinh_cstdtq);


ALTER TABLE IF EXISTS public."DanhHieuHangNam"
    ADD CONSTRAINT "DanhHieuHangNam_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "DanhHieuHangNam_so_quyet_dinh_idx"
    ON public."DanhHieuHangNam"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."DonViTrucThuoc"
    ADD CONSTRAINT "DonViTrucThuoc_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."HoSoCongHien"
    ADD CONSTRAINT "HoSoCongHien_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "HoSoCongHien_quan_nhan_id_key"
    ON public."HoSoCongHien"(quan_nhan_id);


ALTER TABLE IF EXISTS public."HoSoDonViHangNam"
    ADD CONSTRAINT "HoSoDonViHangNam_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."HoSoDonViHangNam"
    ADD CONSTRAINT "HoSoDonViHangNam_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."HoSoHangNam"
    ADD CONSTRAINT "HoSoHangNam_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "HoSoHangNam_quan_nhan_id_key"
    ON public."HoSoHangNam"(quan_nhan_id);


ALTER TABLE IF EXISTS public."HoSoNienHan"
    ADD CONSTRAINT "HoSoNienHan_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "HoSoNienHan_quan_nhan_id_key"
    ON public."HoSoNienHan"(quan_nhan_id);


ALTER TABLE IF EXISTS public."HuanChuongQuanKyQuyetThang"
    ADD CONSTRAINT "HuanChuongQuanKyQuyetThang_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "HuanChuongQuanKyQuyetThang_quan_nhan_id_key"
    ON public."HuanChuongQuanKyQuyetThang"(quan_nhan_id);


ALTER TABLE IF EXISTS public."HuanChuongQuanKyQuyetThang"
    ADD CONSTRAINT "HuanChuongQuanKyQuyetThang_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "HuanChuongQuanKyQuyetThang_so_quyet_dinh_idx"
    ON public."HuanChuongQuanKyQuyetThang"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."KhenThuongDotXuat"
    ADD CONSTRAINT "KhenThuongDotXuat_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."KhenThuongDotXuat"
    ADD CONSTRAINT "KhenThuongDotXuat_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."KhenThuongDotXuat"
    ADD CONSTRAINT "KhenThuongDotXuat_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."KhenThuongDotXuat"
    ADD CONSTRAINT "KhenThuongDotXuat_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "KhenThuongDotXuat_so_quyet_dinh_idx"
    ON public."KhenThuongDotXuat"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."KhenThuongHCBVTQ"
    ADD CONSTRAINT "KhenThuongHCBVTQ_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "KhenThuongHCBVTQ_quan_nhan_id_key"
    ON public."KhenThuongHCBVTQ"(quan_nhan_id);


ALTER TABLE IF EXISTS public."KhenThuongHCBVTQ"
    ADD CONSTRAINT "KhenThuongHCBVTQ_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "KhenThuongHCBVTQ_so_quyet_dinh_idx"
    ON public."KhenThuongHCBVTQ"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."KhenThuongHCCSVV"
    ADD CONSTRAINT "KhenThuongHCCSVV_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."KhenThuongHCCSVV"
    ADD CONSTRAINT "KhenThuongHCCSVV_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "KhenThuongHCCSVV_so_quyet_dinh_idx"
    ON public."KhenThuongHCCSVV"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."KyNiemChuongVSNXDQDNDVN"
    ADD CONSTRAINT "KyNiemChuongVSNXDQDNDVN_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "KyNiemChuongVSNXDQDNDVN_quan_nhan_id_key"
    ON public."KyNiemChuongVSNXDQDNDVN"(quan_nhan_id);


ALTER TABLE IF EXISTS public."KyNiemChuongVSNXDQDNDVN"
    ADD CONSTRAINT "KyNiemChuongVSNXDQDNDVN_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "KyNiemChuongVSNXDQDNDVN_so_quyet_dinh_idx"
    ON public."KyNiemChuongVSNXDQDNDVN"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."LichSuChucVu"
    ADD CONSTRAINT "LichSuChucVu_chuc_vu_id_fkey" FOREIGN KEY (chuc_vu_id)
    REFERENCES public."ChucVu" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."LichSuChucVu"
    ADD CONSTRAINT "LichSuChucVu_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."QuanNhan"
    ADD CONSTRAINT "QuanNhan_chuc_vu_id_fkey" FOREIGN KEY (chuc_vu_id)
    REFERENCES public."ChucVu" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."QuanNhan"
    ADD CONSTRAINT "QuanNhan_co_quan_don_vi_id_fkey" FOREIGN KEY (co_quan_don_vi_id)
    REFERENCES public."CoQuanDonVi" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "QuanNhan_co_quan_don_vi_id_idx"
    ON public."QuanNhan"(co_quan_don_vi_id);


ALTER TABLE IF EXISTS public."QuanNhan"
    ADD CONSTRAINT "QuanNhan_don_vi_truc_thuoc_id_fkey" FOREIGN KEY (don_vi_truc_thuoc_id)
    REFERENCES public."DonViTrucThuoc" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SystemLog"
    ADD CONSTRAINT "SystemLog_nguoi_thuc_hien_id_fkey" FOREIGN KEY (nguoi_thuc_hien_id)
    REFERENCES public."TaiKhoan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."TaiKhoan"
    ADD CONSTRAINT "TaiKhoan_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "TaiKhoan_quan_nhan_id_key"
    ON public."TaiKhoan"(quan_nhan_id);


ALTER TABLE IF EXISTS public."ThanhTichKhoaHoc"
    ADD CONSTRAINT "ThanhTichKhoaHoc_quan_nhan_id_fkey" FOREIGN KEY (quan_nhan_id)
    REFERENCES public."QuanNhan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."ThanhTichKhoaHoc"
    ADD CONSTRAINT "ThanhTichKhoaHoc_so_quyet_dinh_fkey" FOREIGN KEY (so_quyet_dinh)
    REFERENCES public."FileQuyetDinh" (so_quyet_dinh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "ThanhTichKhoaHoc_so_quyet_dinh_idx"
    ON public."ThanhTichKhoaHoc"(so_quyet_dinh);


ALTER TABLE IF EXISTS public."ThongBao"
    ADD CONSTRAINT "ThongBao_nguoi_nhan_id_fkey" FOREIGN KEY (nguoi_nhan_id)
    REFERENCES public."TaiKhoan" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."ThongBao"
    ADD CONSTRAINT "ThongBao_nhat_ky_he_thong_id_fkey" FOREIGN KEY (nhat_ky_he_thong_id)
    REFERENCES public."SystemLog" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;