module.exports = {
  apps: [
    {
      name: 'be-qlkt',
      cwd: './BE-QLKT',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: './BE-QLKT/.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './BE-QLKT/logs/out.log',
      error_file: './BE-QLKT/logs/error.log',
      merge_logs: true,
    },
    {
      name: 'fe-qlkt',
      cwd: './FE-QLKT',
      script: 'node_modules/.bin/next',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: './FE-QLKT/.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './FE-QLKT/logs/out.log',
      error_file: './FE-QLKT/logs/error.log',
      merge_logs: true,
    },
  ],
};
