export const NOTIFICATION_TYPES = {
  PROPOSAL_SUBMITTED: 'PROPOSAL_SUBMITTED',
  PROPOSAL_APPROVED: 'PROPOSAL_APPROVED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  PROPOSAL_DELETED: 'PROPOSAL_DELETED',

  PERSONNEL_ADDED: 'PERSONNEL_ADDED',
  PERSONNEL_TRANSFERRED: 'PERSONNEL_TRANSFERRED',

  ACHIEVEMENT_APPROVED: 'ACHIEVEMENT_APPROVED',

  AWARD_ADDED: 'AWARD_ADDED',
  AWARD_UPDATED: 'AWARD_UPDATED',
  AWARD_DELETED: 'AWARD_DELETED',
} as const;

export const RESOURCE_TYPES = {
  PERSONNEL: 'personnel',
  PROPOSALS: 'proposals',
  ACHIEVEMENTS: 'achievements',
  AWARDS: 'awards',
} as const;
