package vn.qlkt.notification;

public enum LoaiThongBao {
    PROPOSAL_SUBMITTED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    PROPOSAL_DELETED,
    PERSONNEL_ADDED,
    PERSONNEL_TRANSFERRED,
    ACHIEVEMENT_APPROVED,
    AWARD_ADDED,
    AWARD_UPDATED,
    AWARD_DELETED;
}
